### ISSUE TITLE
Link for OWASP SOC is broken

### ISSUE THREAD

**Issue by saurabhhere** [deepanshu1422/List-Of-Open-Source-Internships-Programs#27]
Both Links (Main & Timeline) for OWASP SOC are broken.

![Capture](https://user-images.githubusercontent.com/60233336/96082505-f4ef9980-0ed8-11eb-9082-b4c04328c146.PNG)

**Comment by saurabhhere** [comment]
@vybhav72954 Can you please tell me what to do to fix this bug? And assign it to me?
Thanks :)

**Comment by deepanshu1422** [comment]
@saurabhhere If possible ,Kindly search wether OWASP programme is running or not , and if it's running then edit the readme.md and open a pull request.

**Comment by saurabhhere** [comment]
@deepanshu1422 I don't think it's running, as there is no information available about it on the internet.

**Comment by vybhav72954** [comment]
@saurabhhere Assigned you the issue, as @deepanshu1422 Clearly stated, you need to first determine whether the program is still running or not.

- If tunning, edit the README.md with a suitable link. Open the PR, make sure to mention the issue number it fixes.

- If the program is no longer active. Make sure that you remove the program from the README.md and issue a PR.

Kindly ensure that the info is correct, else we would be forced to reject the PR. I believe that 24 hours are enough in order to open a PR regarding this. Kindly ensure that you issue PR ASAP.

**Comment by saurabhhere** [comment]
@vybhav72954 @deepanshu1422   Is SOC means Summer of Code in the name or something else. I don't get anything as Summer of Code for OWASP also OWASP comes in Gsoc for Summer of code. There is another CTF competition which is conducted by OWASP (https://owasp.org/2020/06/08/AppSecDaysSoS) but it is different as it is competition, not a programme. So update me whether I have to remove OWASP completely from README.md or not?

**Comment by vybhav72954** [comment]
It actually is OWASP [Code Sprint](https://owasp.org/www-community/initiatives/code_sprint/) I did a bit of research and found that Owasp rather than a standalone event now works alongside GSoC. The CTF event is not something that we will mention in this Repo (you correctly said that it is a competition, not a program). 

I believe that removing OWASP SOC, is the best idea. @deepanshu1422 can you please confirm once.

Meanwhile @saurabhhere, you can start working on PR (Remove OWASP), kindly note that you need to mention which Issue it fixes. And Secondly please notice that any direct push to the master branch might get rejected. The best-case scenario is that you fork the project, make a new branch, change and commit your changes, and open a PR while comparing the forks. (Basic Git Workflow)
